const hospitalData = [
  {
    id: 1,
    name: "Artham Multispeciality Hospital",
    address: "Ahmedabad",
    owner: "Dr Sanjay Rajput",
    type: "Surveillance",
    status: "Completed",
  },
  {
    id: 2,
    name: "Aartham Multispeciality Hospital",
    address: "Ahmedabad",
    owner: "Dr Sanjay Rajput",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 3,
    name: "Medipolis life care LLP",
    address: "Palanpur",
    owner: "Miteshbhai Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 4,
    name: "Lions General Hospital",
    address: "Mahesana",
    owner: "Trustee",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 5,
    name: "Central United Hospital",
    address: "Odhav, Ahmedabad",
    owner: "Dr Parthiv Maheta",
    type: "Quality Accreditation For Large Healthcare Organization",
    status: "Completed",
  },
  {
    id: 6,
    name: "Urban Hospital",
    address: "Dahod",
    owner: "Sheth Sandeepbhai",
    type: "Entry level - Quality Accreditation",
    status: "Completed",
  },
  {
    id: 7,
    name: "Central United Hospital",
    address: "Odhav",
    owner: "Dr Khushboo Sharma",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 8,
    name: "Central United Hospital",
    address: "Ahmedabad",
    owner: "Dr Khushboo Sharma",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 9,
    name: "Ved Hospital",
    address: "Nadiad",
    owner: "Dr Vaibhav Patel",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 10,
    name: "Harmony Hospital",
    address: "Nikol",
    owner: "Dr Paresh Gohel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 11,
    name: "Harmony Hospital",
    address: "Nikol",
    owner: "Dr Kunal Bhatt",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 12,
    name: "Phoenix Hospital",
    address: "Naroda, Ahmedabad",
    owner: "Dr Hitesh Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 13,
    name: "Panchshil Hopital",
    address: "Sabarmati",
    owner: "Dr Kaushik Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 14,
    name: "Phoenix Hospital",
    address: "Naroda",
    owner: "Dr Yogesh Vaghela",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 15,
    name: "Panchshil Hopital",
    address: "Sabarmati",
    owner: "Dr Kaushik Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 16,
    name: "Prism Multispeciality Hospital",
    address: "Ahmedabad",
    owner: "Dr Heena Zargar",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 17,
    name: "Karmdeep Hospital",
    address: "Bapunagar, Ahmedabad",
    owner: "Dr Dilip Pethani",
    type: "Quality Accreditation For Small Healthcare Organisation",
    status: "Completed",
  },
  {
    id: 18,
    name: "Life Line Multispeciality Hospital",
    address: "Gota",
    owner: "Dr Chandresh Sharma",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 19,
    name: "I.G. Memorial Hospital",
    address: "Veraval",
    owner: "Dr Rajesh Ghansani",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 20,
    name: "Karmdeep Hospital",
    address: "Bapunagar",
    owner: "Dr Neha Pethani",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 21,
    name: "I.G. Memorial Hospital",
    address: "Veraval",
    owner: "Dr Rajesh Ghansani",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 22,
    name: "Chanddni Hospital",
    address: "Kota, Rajasthan",
    owner: "Dr Kshitij Soni",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 23,
    name: "ICONIC Hospital International PVT LTD",
    address: "Ahmedabad",
    owner: "Dr Parag Seth",
    type: "Surveillance",
    status: "Completed",
  },
  {
    id: 24,
    name: "Siddhi Hospital",
    address: "Naroda",
    owner: "Dr Sunil Wadhvani",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 25,
    name: "Bhagwati General Hospital",
    address: "Vastral, Ahmedabad",
    owner: "Dr Rahul Mali",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 26,
    name: "Sangani Hospital",
    address: "Keshod",
    owner: "Dr Ajay Sangani",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 27,
    name: "Sangani Super Speciality Hospitals Pvt Ltd",
    address: "Veraval",
    owner: "Dr Rajesh Sangnai",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 28,
    name: "Shailya Hospital",
    address: "Naranpura",
    owner: "Dr Kaushal Anand",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 29,
    name: "Hridyam Heart Hospital",
    address: "Himmatnagar",
    owner: "Dr Ronak Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 30,
    name: "Karmdeep orthopedic & skin hospital",
    address: "Bapunagar",
    owner: "Dr Neha Pethani",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 31,
    name: "Nadiad ICU & Multi Superspeciality",
    address: "Nadiad",
    owner: "Dr Jatin Lathiya",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 32,
    name: "Bhagwati General Hospital",
    address: "Ahmedabad",
    owner: "Dr Rahul Mali",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 33,
    name: "Karmdeep Hospital",
    address: "Ahmedabad",
    owner: "Dr Neha Pethani",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 34,
    name: "Shailya Hospital",
    address: "Ahmedabad",
    owner: "Dr Kaushal Anand",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 35,
    name: "Bhagwati General Hospital",
    address: "Ahmedabad",
    owner: "Dr Rahul Mali",
    type: "Renewal",
    status: "In Process",
  },
  {
    id: 36,
    name: "Apple Heart Hospital",
    address: "Mehsana",
    owner: "Dr Alap Patel",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 37,
    name: "Global Hospital",
    address: "Surat",
    owner: "Dr Yogesh Kalathiya",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 38,
    name: "Apex Hospital",
    address: "Kosamba",
    owner: "Dr Anis Surti",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 39,
    name: "Jankalyan Hospital",
    address: "Shah e alam",
    owner: "Dr Jitendra Shukla",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 40,
    name: "Samata Multispeciality Hospital",
    address: "Chandlodiya, Ahmedabad",
    owner: "Dr Narendra Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 41,
    name: "Rushabh Medi Surge Hospital",
    address: "Satellite",
    owner: "Dr Hardik Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 42,
    name: "Samata Multispeciality Hospital",
    address: "Chandlodiya",
    owner: "Dr N J Shah",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 43,
    name: "Krishna Hospital & ICCU",
    address: "Ahmedabad",
    owner: "Dr Harshad Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 44,
    name: "Shri Vikalp Hospital",
    address: "Ugat",
    owner: "Dr Pooja Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 45,
    name: "Samata Multispeciality Hospital",
    address: "Chandlodiya",
    owner: "Dr Kinnav Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 46,
    name: "Shri Vikalp Hospital",
    address: "Surat",
    owner: "Dr Pooja Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 47,
    name: "Krishna Hospital & ICCU",
    address: "Ahmedabad",
    owner: "Dr Harshad Patel",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 48,
    name: "Life Line Multispeciality Hospital",
    address: "Gota",
    owner: "Dr Chandresh Sharma",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 49,
    name: "Shubh Multispeciality Hospital",
    address: "Kalol",
    owner: "Dr Ajay Gajjar",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 50,
    name: "Araf General Hospital",
    address: "Kosamba",
    owner: "Dr Sahir Araf",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 51,
    name: "Siddhi Hospital",
    address: "Kubernagar, Ahmedabad",
    owner: "Dr Nirmala Wadhwani",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 52,
    name: "Livewell Hospital",
    address: "Ahmedabad",
    owner: "Dr Hitesh Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 53,
    name: "Shailya Hospital",
    address: "Naranpura, Ahmedabad",
    owner: "Dr Amit Trivedi",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 54,
    name: "Avadh Multispeciality Hospital",
    address: "Vastral, Ahmedabad",
    owner: "Dr Brijesh Vala",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 55,
    name: "Global Hospital, Sarthana Jakatnaka",
    address: "Surat",
    owner: "Dr Milan Dhaduk",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 56,
    name: "Avadh Multispeciality Hospital",
    address: "Vastral",
    owner: "Dr Hitesh Prajapati",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 57,
    name: "Asian Super speciality Hospitals Pvt Ltd",
    address: "Navrangpura",
    owner: "Dr Bhavesh Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 58,
    name: "Phoenix Emergency & Critical care Hospital",
    address: "Bhuyangdev",
    owner: "Dr Yogesh Vaghela",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 59,
    name: "Anubhav Hospital",
    address: "Katargam",
    owner: "Dr Rahul Kalathiya",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 60,
    name: "City Life Care Multispeciality Hospital",
    address: "Surat",
    owner: "Dr Ankit Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 61,
    name: "Shraddha Hospital",
    address: "Kalol",
    owner: "Dr Rajat Engineer",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 62,
    name: "Ocean Multispeciality Hospital",
    address: "Narol",
    owner: "Dr Sanjaysinh Tomar",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 63,
    name: "Ved Hospital",
    address: "Kheda",
    owner: "Dr Vaibhav Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 64,
    name: "Aditya Multispeciality Hospital",
    address: "Ahmedabad",
    owner: "Dr Naresh Malhotra",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 65,
    name: "Gastroplus Hospital",
    address: "Nikol, Ahmedabad",
    owner: "Ms. Rukshar Kheradawala",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 66,
    name: "Yashikas Lifecare Hospital",
    address: "Kosamba, Surat",
    owner: "Dr Bharat Gramani",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 67,
    name: "Shraddha Hospital",
    address: "Kalol",
    owner: "Dr Rajat Engineer",
    type: "Renewal",
    status: "In Process",
  },
  {
    id: 68,
    name: "Asian Supespeciality Hospital",
    address: "Ahmedabad",
    owner: "Dr Bhupesh Patel",
    type: "Renewal",
    status: "In Process",
  },
  {
    id: 69,
    name: "Rangam Multispeciality Hospitl",
    address: "Ahmedabad",
    owner: "Dr Rudresh Pandya",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 70,
    name: "Ashirwad Multispeciality Hospital",
    address: "Kosamba",
    owner: "Dr Nirav Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 71,
    name: "Life Care Hospital",
    address: "Nikol",
    owner: "Dr Raj Sharma",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 72,
    name: "Gastroplus Digestive Disease Centre Private Limited",
    address: "Vastrapur, Ahmedabad",
    owner: "Ms. Rukshar Kheradawala",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 73,
    name: "Kheteshwar Hospital",
    address: "Ahmedabad",
    owner: "Dr Govind Purohit",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 74,
    name: "Aditi hospital & Diagnostics",
    address: "Bopal",
    owner: "Dr Mahesh Makvana",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 75,
    name: "Tirupati General Hospital",
    address: "Akhbarnagar",
    owner: "Dr Arun Sheth",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 76,
    name: "Sumiran IVF Centre",
    address: "Naranpura, Ahmedabad",
    owner: "Dr Mehul Sukhadiya",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 77,
    name: "Apurva Hospital",
    address: "Surat",
    owner: "Dr Rinki Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 78,
    name: "Soni Clinic",
    address: "Ankleshwar",
    owner: "Dr Mahendra Soni",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 79,
    name: "Aarna Medical Hospital",
    address: "Bapunagar",
    owner: "Dr Paresh Gohel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 80,
    name: "Sparsh Multispeciality Hospital",
    address: "Vatva",
    owner: "Dr Nimesh Prajapati",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 81,
    name: "Maitri Eye Hospital",
    address: "Maheshana",
    owner: "Dr Mukesh Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 82,
    name: "Aarna Medical Hospital",
    address: "Bapunagar",
    owner: "Dr Paresh Gohel",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 83,
    name: "Maitri Eye Hospital",
    address: "Maheshana",
    owner: "Dr Mukesh Patel",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 84,
    name: "Aarna Medical Hospital",
    address: "Ahmedabad",
    owner: "Dr Paresh Gohel",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 85,
    name: "Shukan Hospital & IVF Center",
    address: "Sola, Ahmedabad",
    owner: "Dr Praksh Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 86,
    name: "Aashwi ENT Hospital",
    address: "Vastrapur",
    owner: "Dr Mihir Mehta",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 87,
    name: "Shri Rang Ayurvedic Hospital",
    address: "Paldi",
    owner: "Dr Tejas Patel/Dr Indubhai Dave",
    type: "Quality Accreditation For Shalya Karma Hospital",
    status: "Completed",
  },
  {
    id: 88,
    name: "Aashwi ENT Hospital",
    address: "Vastrapur",
    owner: "Dr Manish Goyal",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 89,
    name: "Mamta Hospital",
    address: "Surat",
    owner: "Dr Jignesh Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 90,
    name: "Shukan Hospital & IVF Center",
    address: "Sola",
    owner: "Dr Ajay Prajapati",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 91,
    name: "Shrirang Hospital & Research center",
    address: "Paldi",
    owner: "Dr Tejas Patel",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 92,
    name: "Sukan Hospital",
    address: "Ahmedabad",
    owner: "Dr Ajay Prajapati",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 93,
    name: "Shree Raj Hospital",
    address: "Bopal, Ahmedabad",
    owner: "Dr Pritesh Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 94,
    name: "Aagyarth Ayurved Hospital",
    address: "Ambavadi, Ahmedabad",
    owner: "Dr Milan Prajapati",
    type: "Quality Accreditation For Panchkarma Clinic",
    status: "Completed",
  },
  {
    id: 95,
    name: "Aniket Children Hospital",
    address: "CTM, Ahmedabad",
    owner: "Dr Bina Gajjar",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 96,
    name: "Shree Krishna Hospital & Heart care",
    address: "Gurukul, Ahmedabad",
    owner: "Dr Nehal Sadhu",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 97,
    name: "Rhythm Heart & Medical Hospital",
    address: "Chandkheda, Ahmedabad",
    owner: "Dr Hilesh Diwan",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 98,
    name: "Anjani Maternity Home",
    address: "Ankleshwar",
    owner: "Dr Aarjav Dave",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 99,
    name: "Aagyarth Ayurved & Panchkarma Hospital",
    address: "Ambawadi",
    owner: "Dr Niharika Prajapati",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 100,
    name: "Aniket Children Hospital",
    address: "CTM",
    owner: "Dr Bina Gajjar",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 101,
    name: "Shivasya Hospital",
    address: "Navrangpura",
    owner: "Dr Amit Trivedi",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 102,
    name: "Orthoplus Hospital",
    address: "Bhuyangdev",
    owner: "Dr Yogesh Vaghela",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 103,
    name: "Jincy Multispeciality Hospital",
    address: "Chandkheda",
    owner: "Dr Dhiraj Makwana",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 104,
    name: "Anjani Maternity Home",
    address: "Ankleshwar",
    owner: "Dr Bhoomi Dave",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 105,
    name: "Prarthna Hospital",
    address: "Surat",
    owner: "Dr Nitin Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 106,
    name: "Well care Hospital",
    address: "Surat",
    owner: "Dr Shalinikumari",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 107,
    name: "Jeevan Jyoti Hospital",
    address: "Surat",
    owner: "Dr Alpa Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 108,
    name: "Jatan ENT Hospital",
    address: "Himmatnagar",
    owner: "Dr Darshak Dharajiya",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 109,
    name: "Vihaan Hospitals Pvt Ltd",
    address: "Bhadaj",
    owner: "Dr Lokendra Rathor",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 110,
    name: "Jay Multispeciality Hospital",
    address: "Rajkot",
    owner: "Dr Urmika Thoria",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 111,
    name: "Pahal Hospital",
    address: "Surat",
    owner: "Dr Purvi Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 112,
    name: "Tulip Hospital",
    address: "Ahmedabad",
    owner: "Dr Manish Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 113,
    name: "Evara Hospital",
    address: "Gandhinagar",
    owner: "Dr Niraj Suri",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 114,
    name: "Aniket Children Hospital",
    address: "Ahmedabad",
    owner: "Dr Beena Gajjar",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 115,
    name: "Alfa Gastor & Liver Care",
    address: "Ahmedabad",
    owner: "Dr Vatsal Mehta",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 116,
    name: "Dheeraj Hospital",
    address: "Patan",
    owner: "Dr Vipul Soni",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 117,
    name: "Shivasya Hospital",
    address: "Ahmedabad",
    owner: "Dr Amit Trivedi",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 118,
    name: "Orthoplus Hospital",
    address: "Ahmedabad",
    owner: "Dr Pratik Shah",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 119,
    name: "Sattva Orthopedic & ENT Hospital",
    address: "Ahmedabad",
    owner: "Dr Satvik Patel",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 120,
    name: "Anjani Maternity Hospital",
    address: "Ankleshwar",
    owner: "Dr Bhoomi Dave",
    type: "Renewal",
    status: "In Process",
  },
  {
    id: 121,
    name: "Rhythm Heart & Medical Hospital",
    address: "Chandkheda",
    owner: "Dr Hilesh Diwan",
    type: "Renewal",
    status: "In Process",
  },
  {
    id: 122,
    name: "New Life Hospital",
    address: "Akhbarnagar",
    owner: "Dr Monil Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 123,
    name: "Sheth Hospital & Maternity Home",
    address: "Paldi",
    owner: "Dr Ami Sheth",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 124,
    name: "Siddhi Vinayak Hospital",
    address: "Paladi, Ahmedabad",
    owner: "Dr Viren Rajyaguru",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 125,
    name: "Siddhi Vinayak Hospital",
    address: "Ambawadi",
    owner: "Dr Viren Rajyaguru",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 126,
    name: "Ansh Clinic",
    address: "Ahmedabad",
    owner: "Dr Sanjay Rajput",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 127,
    name: "Ansh Clinic",
    address: "Ahmedabad",
    owner: "Dr Sanjay Rajput",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 128,
    name: "Aniket ENT Hospital",
    address: "CTM, Ahmedabad",
    owner: "Dr Jayesh Gajjar",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 129,
    name: "Dr Saurabh shah ortho. Hospital",
    address: "Naranpura, Ahmedabad",
    owner: "Dr Saurabh shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 130,
    name: "Aniket ENT Hospital",
    address: "CTM",
    owner: "Dr Jayesh Gajjar",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 131,
    name: "Dr Saurabh shah ortho. Hospital",
    address: "Naranpura",
    owner: "Dr Saurabh shah",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 132,
    name: "Aniket ENT Hospital",
    address: "CTM, Ahmedabad",
    owner: "Dr Jayesh Gajjar",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 133,
    name: "L & T Diagnostic Centre",
    address: "Vadodara",
    owner: "Mr Rushikesh Mistry",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 134,
    name: "J P Hospital",
    address: "Sola, Ahmedabad",
    owner: "Dr Jay Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 135,
    name: "Mehta Eye Hospital",
    address: "Rajkot",
    owner: "Dr Ajay Mehta",
    type: "Renewal/ Maintenance",
    status: "In Process",
  },
  {
    id: 136,
    name: "Neepa ENT Hospital",
    address: "Surat",
    owner: "Dr Neepa Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 137,
    name: "Garvit ENT Hospital",
    address: "Surat",
    owner: "Dr Harit Trivedi",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 138,
    name: "Sadbhaav Eye & Dental Hospital",
    address: "Motera",
    owner: "Dr Dhaval Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 139,
    name: "Sankalp Ayurved Hospital",
    address: "Akhbarnagar",
    owner: "Dr Sunil Suthar",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 140,
    name: "Garvit ENT Hospital",
    address: "Surat",
    owner: "Dr Harit Trivedi",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 141,
    name: "Krishna Ayurvedam Panchakarma Hospital",
    address: "Ahmedabad",
    owner: "Dr Digish Thakkar",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 142,
    name: "Dr Piyush Ayurveda",
    address: "Ahmedabad",
    owner: "Dr Piyush Patel",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 143,
    name: "Dr Agravat Wellness Centre",
    address: "Ahmedabad",
    owner: "Dr Jaman Agravat",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 144,
    name: "Urmi Eye Hospital",
    address: "Surat",
    owner: "Dr Anil Patel",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 145,
    name: "Eye Care Hospital Pvt Lttd.",
    address: "Ambavadi, Ahmedabad",
    owner: "Dr Shashank Rathod",
    type: "Quality Accreditation For Eye Care Organisation",
    status: "Completed",
  },
  {
    id: 146,
    name: "Eye Care Hospital Pvt Lttd.",
    address: "Ambawadi",
    owner: "Dr Shashank Rathod",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 147,
    name: "Akshar Eye Hospital",
    address: "Naroda",
    owner: "Dr Jethanand Vidhani",
    type: "Renewal",
    status: "Completed",
  },
  {
    id: 148,
    name: "Parshwa Dental Clinic",
    address: "Ahmedabad",
    owner: "Dr Shrenik Shah",
    type: "Quality Accreditation",
    status: "In Process",
  },
  {
    id: 149,
    name: "Dr Shah's Eye Superspeciality Hospital",
    address: "Ambawadi",
    owner: "Dr Sapan Shah",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 150,
    name: "Sight Vision Eye Hospital & Lasik Center",
    address: "Surat",
    owner: "Dr Binita Gandhi",
    type: "Quality Accreditation",
    status: "Completed",
  },
  {
    id: 151,
    name: "Spectrum Advanced Eye Care Hospital",
    address: "Surat",
    owner: "Dr Nitin Garg",
    type: "Quality Accreditation",
    status: "In Process",
  },
];
