const hospitalData = [
    { id: 1, name: "Karmdeep Hospital", address: "Bapunagar", owner: "Dr Dilip Pethani", type: "Quality Accreditation (SHCO)", status: "Completed" },
    { id: 2, name: "Shree Raj Hospital", address: "Bopal", owner: "Dr Pritesh Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 3, name: "Aagyarth Ayurved Hospital", address: "Ambavadi", owner: "Dr Milan Prajapati", type: "Panchkarma Clinic", status: "Completed" },
    { id: 4, name: "Aniket ENT Hospital", address: "CTM", owner: "Dr Jayesh Gajjar", type: "Quality Accreditation", status: "Completed" },
    { id: 5, name: "Aniket Children Hospital", address: "CTM", owner: "Dr Bina Gajjar", type: "Quality Accreditation", status: "Completed" },
    { id: 6, name: "Samata Multispeciality Hospital", address: "Chandlodiya", owner: "Dr Narendra Shah", type: "Quality Accreditation", status: "Completed" },
    { id: 7, name: "Shree Krishna Hospital & Heart care", address: "Gurukul", owner: "Dr Nehal Sadhu", type: "Quality Accreditation", status: "Completed" },
    { id: 8, name: "Siddhi Hospital", address: "Kubernagar", owner: "Dr Nirmala Wadhwani", type: "Quality Accreditation", status: "Completed" },
    { id: 9, name: "Dr Saurabh shah ortho. Hospital", address: "Naranpura", owner: "Dr Saurabh shah", type: "Quality Accreditation", status: "Completed" },
    { id: 10, name: "Shukan Hospital & IVF Center", address: "Sola", owner: "Dr Prakash Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 11, name: "Central United Hospital", address: "Odhav", owner: "Dr Parthiv Maheta", type: "Quality Accreditation (Large)", status: "Completed" },
    { id: 12, name: "Eye Care Hospital Pvt Ltd.", address: "Ambavadi", owner: "Dr Shashank Rathod", type: "Eye Care Organisation", status: "Completed" },
    { id: 13, name: "Bhagwati General Hospital", address: "Vastral", owner: "Dr Rahul Mali", type: "Quality Accreditation", status: "Completed" },
    { id: 14, name: "Phoenix Hospital", address: "Naroda", owner: "Dr Hitesh Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 15, name: "Shailya Hospital", address: "Naranpura", owner: "Dr Amit Trivedi", type: "Quality Accreditation", status: "Completed" },
    { id: 16, name: "Avadh Multispeciality Hospital", address: "Vastral", owner: "Dr Brijesh Vala", type: "Quality Accreditation", status: "Completed" },
    { id: 17, name: "Rhythm Heart & Medical Hospital", address: "Chandkheda", owner: "Dr Hilesh Diwan", type: "Quality Accreditation", status: "Completed" },
    { id: 18, name: "Siddhi Vinayak Hospital", address: "Paladi", owner: "Dr Viren Rajyaguru", type: "Quality Accreditation", status: "Completed" },
    { id: 19, name: "Sumiran IVF Centre", address: "Naranpura", owner: "Dr Mehul Sukhadiya", type: "Quality Accreditation", status: "Completed" },
    { id: 20, name: "Aarna Medical Hospital", address: "Bapunagar", owner: "Dr Paresh Gohel", type: "Quality Accreditation", status: "Completed" },
    { id: 21, name: "Aashwi ENT Hospital", address: "Vastrapur", owner: "Dr Mihir Mehta", type: "Quality Accreditation", status: "Completed" },
    { id: 22, name: "Sparsh Multispeciality Hospital", address: "Vatva", owner: "Dr Nimesh Prajapati", type: "Quality Accreditation", status: "Completed" },
    { id: 23, name: "Tirupati General Hospital", address: "Akhbarnagar", owner: "Dr Arun Sheth", type: "Quality Accreditation", status: "Completed" },
    { id: 24, name: "Rushabh Medi Surge Hospital", address: "Satellite", owner: "Dr Hardik Shah", type: "Quality Accreditation", status: "Completed" },
    { id: 25, name: "Sangani Hospital", address: "Keshod", owner: "Dr Ajay Sangani", type: "Quality Accreditation", status: "Completed" },
    { id: 27, name: "Shri Rang Ayurvedic Hospital", address: "Paldi", owner: "Dr Tejas Patel/Indubhai Dave", type: "Shalya Karma Hospital", status: "Completed" },
    { id: 28, name: "Sangani Super Speciality", address: "Veraval", owner: "Dr Rajesh Sangnai", type: "Quality Accreditation", status: "Completed" },
    { id: 29, name: "Hospitals Pvt Ltd (Harmony)", address: "Nikol", owner: "Dr Paresh Gohel", type: "Quality Accreditation", status: "Completed" },
    { id: 30, name: "New Life Hospital", address: "Akhbarnagar", owner: "Dr Monil Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 31, name: "Aditi hospital & Diagnostics", address: "Bopal", owner: "Dr Mahesh Makvana", type: "Quality Accreditation", status: "Completed" },
    { id: 32, name: "Anjani Maternity Home", address: "Ankleshwar", owner: "Dr Aarjav Dave", type: "Quality Accreditation", status: "Completed" },
    { id: 33, name: "Sheth Hospital & Maternity Home", address: "Paldi", owner: "Dr Ami Sheth", type: "Quality Accreditation", status: "Completed" },
    { id: 34, name: "Life Line Multispeciality Hospital", address: "Gota", owner: "Dr Chandresh Sharma", type: "Quality Accreditation", status: "Completed" },
    { id: 35, name: "Maitri Eye Hospital", address: "Maheshana", owner: "Dr Mukesh Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 36, name: "Garvit ENT Hospital", address: "Surat", owner: "Dr Harit Trivedi", type: "Quality Accreditation", status: "Completed" },
    { id: 37, name: "Global Hospital", address: "Surat", owner: "Dr Yogesh Kalathiya", type: "Quality Accreditation", status: "Completed" },
    { id: 38, name: "Global Hospital, Sarthana", address: "Surat", owner: "Dr Milan Dhaduk", type: "Quality Accreditation", status: "Completed" },
    { id: 39, name: "I.G. Memorial Hospital", address: "Veraval", owner: "Dr Rajesh Ghansani", type: "Quality Accreditation", status: "Completed" },
    { id: 40, name: "Aagyarth Ayurved & Panchkarma", address: "Ambawadi", owner: "Dr Niharika Prajapati", type: "Quality Accreditation", status: "Completed" },
    { id: 41, name: "Samata Multispeciality Hospital", address: "Chandlodiya", owner: "Dr N J Shah", type: "Renewal", status: "Completed" },
    { id: 42, name: "Karmdeep Hospital", address: "Bapunagar", owner: "Dr Neha Pethani", type: "Renewal", status: "Completed" },
    { id: 43, name: "Aniket ENT Hospital", address: "CTM", owner: "Dr Jayesh Gajjar", type: "Renewal", status: "Completed" },
    { id: 44, name: "Aniket Children Hospital", address: "CTM", owner: "Dr Bina Gajjar", type: "Renewal", status: "Completed" },
    { id: 45, name: "Shailya Hospital", address: "Naranpura", owner: "Dr Kaushal Anand", type: "Renewal", status: "Completed" },
    { id: 46, name: "Avadh Multispeciality Hospital", address: "Vastral", owner: "Dr Hitesh Prajapati", type: "Renewal", status: "Completed" },
    { id: 47, name: "Aarna Medical Hospital", address: "Bapunagar", owner: "Dr Paresh Gohel", type: "Renewal", status: "Completed" },
    { id: 48, name: "Eye Care Hospital Pvt Ltd.", address: "Ambawadi", owner: "Dr Shashank Rathod", type: "Renewal", status: "Completed" },
    { id: 49, name: "Sadbhaav Eye & Dental Hospital", address: "Motera", owner: "Dr Dhaval Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 50, name: "Panchshil Hopital", address: "Sabarmati", owner: "Dr Kaushik Shah", type: "Quality Accreditation", status: "Completed" },
    { id: 51, name: "Neepa ENT Hospital", address: "Surat", owner: "Dr Neepa Shah", type: "Quality Accreditation", status: "Completed" },
    { id: 52, name: "Hridyam Heart Hospital", address: "Himmatnagar", owner: "Dr Ronak Shah", type: "Quality Accreditation", status: "Completed" },
    { id: 53, name: "Shivasya Hospital", address: "Navrangpura", owner: "Dr Amit Trivedi", type: "Quality Accreditation", status: "Completed" },
    { id: 54, name: "Orthoplus Hospital", address: "Bhuyangdev", owner: "Dr Yogesh Vaghela", type: "Quality Accreditation", status: "Completed" },
    { id: 55, name: "Jincy Multispeciality Hospital", address: "Chandkheda", owner: "Dr Dhiraj Makwana", type: "Quality Accreditation", status: "Completed" },
    { id: 56, name: "Siddhi Vinayak Hospital", address: "Ambawadi", owner: "Dr Viren Rajyaguru", type: "Renewal", status: "Completed" },
    { id: 57, name: "Apurva Hospital", address: "Surat", owner: "Dr Rinki Shah", type: "Quality Accreditation", status: "Completed" },
    { id: 58, name: "Asian Super speciality Hospitals", address: "Navrangpura", owner: "Dr Bhavesh Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 59, name: "Jankalyan Hospital", address: "Shah e alam", owner: "Dr Jitendra Shukla", type: "Quality Accreditation", status: "Completed" },
    { id: 60, name: "Krishna Hospital & ICCU", address: "Ahmedabad", owner: "Dr Harshad Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 61, name: "Phoenix Emergency & Critical care", address: "Bhuyangdev", owner: "Dr Yogesh Vaghela", type: "Quality Accreditation", status: "Completed" },
    { id: 62, name: "Karmdeep orthopedic & skin", address: "Bapunagar", owner: "Dr Neha Pethani", type: "Renewal", status: "Completed" },
    { id: 63, name: "Dr Shah's Eye Hospital", address: "Ambawadi", owner: "Dr Sapan Shah", type: "Quality Accreditation", status: "Completed" },
    { id: 64, name: "Anubhav Hospital", address: "Katargam", owner: "Dr Rahul Kalathiya", type: "Quality Accreditation", status: "Completed" },
    { id: 65, name: "Shri Vikalp Hospital", address: "Ugat", owner: "Dr Pooja Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 66, name: "Sankalp Ayurved Hospital", address: "Akhbarnagar", owner: "Dr Sunil Suthar", type: "Quality Accreditation", status: "Completed" },
    { id: 67, name: "Araf General Hospital", address: "Kosamba", owner: "Dr Sahir Araf", type: "Quality Accreditation", status: "Completed" },
    { id: 68, name: "City Life Care Hospital", address: "Surat", owner: "Dr Ankit Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 69, name: "Shraddha Hospital", address: "Kalol", owner: "Dr Rajat Engineer", type: "Quality Accreditation", status: "Completed" },
    { id: 70, name: "Dr Saurabh shah ortho. Hospital", address: "Naranpura", owner: "Dr Saurabh shah", type: "Renewal", status: "Completed" },
    { id: 71, name: "Medipolis life care LLP", address: "Palanpur", owner: "Miteshbhai Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 72, name: "Anjani Maternity Home", address: "Ankleshwar", owner: "Dr Bhoomi Dave", type: "Renewal", status: "Completed" },
    { id: 73, name: "Prarthna Hospital", address: "Surat", owner: "Dr Nitin Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 74, name: "Ashirwad Multispeciality", address: "Kosamba", owner: "Dr Nirav Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 75, name: "Well care Hospital", address: "Surat", owner: "Dr Shalinikumari", type: "Quality Accreditation", status: "Completed" },
    { id: 76, name: "Samata Multispeciality Hospital", address: "Chandlodiya", owner: "Dr Kinnav Shah", type: "Quality Accreditation", status: "Completed" },
    { id: 77, name: "Central United Hospital", address: "Odhav", owner: "Dr Khushboo Sharma", type: "Quality Accreditation", status: "Completed" },
    { id: 78, name: "Nadiad ICU & Multi Superspeciality", address: "Nadiad", owner: "Dr Jatin Lathiya", type: "Quality Accreditation", status: "Completed" },
    { id: 79, name: "Siddhi Hospital", address: "Naroda", owner: "Dr Sunil Wadhvani", type: "Quality Accreditation", status: "Completed" },
    { id: 80, name: "Shri Vikalp Hospital", address: "Surat", owner: "Dr Pooja Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 81, name: "Sight Vision Eye & Lasik", address: "Surat", owner: "Dr Binita Gandhi", type: "Quality Accreditation", status: "Completed" },
    { id: 82, name: "Bhagwati General Hospital", address: "Ahmedabad", owner: "Dr Rahul Mali", type: "Renewal", status: "Completed" },
    { id: 83, name: "Kheteshwar Hospital", address: "Ahmedabad", owner: "Dr Govind Purohit", type: "Quality Accreditation", status: "Completed" },
    { id: 84, name: "Jeevan Jyoti Hospital", address: "Surat", owner: "Dr Alpa Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 85, name: "Jatan ENT Hospital", address: "Himmatnagar", owner: "Dr Darshak Dharajiya", type: "Quality Accreditation", status: "Completed" },
    { id: 86, name: "Phoenix Hospital Naroda", address: "Naroda", owner: "Dr Yogesh Vaghela", type: "Renewal", status: "Completed" },
    { id: 87, name: "Aashwi ENT Hospital", address: "Vastrapur", owner: "Dr Manish Goyal", type: "Renewal", status: "Completed" },
    { id: 88, name: "Mamta Hospital", address: "Surat", owner: "Dr Jignesh Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 89, name: "Urmi Eye Hospital", address: "Surat", owner: "Dr Anil Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 90, name: "Shukan Hospital & IVF Center", address: "Sola", owner: "Dr Ajay Prajapati", type: "Quality Accreditation", status: "Completed" },
    { id: 91, name: "Vihaan Hospitals Pvt Ltd", address: "Bhadaj", owner: "Dr Lokendra Rathor", type: "Quality Accreditation", status: "Completed" },
    { id: 92, name: "Ocean Multispeciality Hospital", address: "Narol", owner: "Dr Sanjaysinh Tomar", type: "Quality Accreditation", status: "Completed" },
    { id: 93, name: "Akshar Eye Hospital", address: "Naroda", owner: "Dr Jethanand Vidhani", type: "Renewal", status: "Completed" },
    { id: 94, name: "Aniket ENT Hospital", address: "Ahmedabad", owner: "Dr Jayesh Gajjar", type: "Renewal", status: "Completed" },
    { id: 95, name: "Maitri Eye Hospital", address: "Maheshana", owner: "Dr Mukesh Patel", type: "Renewal", status: "Completed" },
    { id: 96, name: "Shrirang Hospital & Research", address: "Paldi", owner: "Dr Tejas Patel", type: "Renewal", status: "Completed" },
    { id: 97, name: "Harmony Hospital", address: "Nikol", owner: "Dr Kunal Bhatt", type: "Renewal", status: "Completed" },
    { id: 98, name: "Akshar Eye Hospital", address: "Naroda", owner: "Dr Jethanand Vidhani", type: "Renewal", status: "Completed" },
    { id: 99, name: "Garvit ENT Hospital", address: "Surat", owner: "Dr Harit Trivedi", type: "Renewal", status: "Completed" },
    { id: 100, name: "Apex Hospital", address: "Kosamba", owner: "Dr Anis Surti", type: "Quality Accreditation", status: "Completed" },
    { id: 101, name: "Aartham Hospital", address: "Ahmedabad", owner: "Dr Sanjay Rajput", type: "Renewal", status: "Completed" },
    { id: 102, name: "Ansh Clinic", address: "Ahmedabad", owner: "Dr Sanjay Rajput", type: "Renewal", status: "Completed" },
    { id: 103, name: "Ved Hospital", address: "Kheda", owner: "Dr Vaibhav Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 104, name: "Jay Multispeciality Hospital", address: "Rajkot", owner: "Dr Urmika Thoria", type: "Quality Accreditation", status: "Completed" },
    { id: 105, name: "Life Care Hospital", address: "Nikol", owner: "Dr Raj Sharma", type: "Quality Accreditation", status: "Completed" },
    { id: 106, name: "Pahal Hospital", address: "Surat", owner: "Dr Purvi Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 107, name: "Urban Hospital", address: "Dahod", owner: "Sheth Sandeepbhai", type: "Quality Accreditation", status: "Completed" },
    { id: 108, name: "Krishna Hospital & ICCU", address: "Ahmedabad", owner: "Dr Harshad Patel", type: "Renewal", status: "Completed" },
    { id: 109, name: "Livewell Hospital", address: "Ahmedabad", owner: "Dr Hitesh Patel", type: "Quality Accreditation", status: "Completed" },
    { id: 110, name: "Soni Clinic", address: "Ankleshwar", owner: "Dr Mahendra Soni", type: "Quality Accreditation", status: "Completed" },
    { id: 111, name: "Sukan Hospital", address: "Ahmedabad", owner: "Dr Ajay Prajapati", type: "Renewal", status: "Completed" },
    { id: 112, name: "Tulip Hospital", address: "Ahmedabad", owner: "Dr Manish Shah", type: "Quality Accreditation", status: "Completed" },
    { id: 113, name: "Aditya Multispeciality Hospital", address: "Ahmedabad", owner: "Dr Naresh Malhotra", type: "Quality Accreditation", status: "Completed" },
    { id: 114, name: "Aarna Medical Hospital", address: "Ahmedabad", owner: "Dr Paresh Gohel", type: "Renewal", status: "Completed" },
    { id: 115, name: "Central United Hospital", address: "Ahmedabad", owner: "Dr Khushboo Sharma", type: "Renewal", status: "Completed" },
    { id: 116, name: "Life Line Multispeciality Hospital", address: "Gota", owner: "Dr Chandresh Sharma", type: "Renewal", status: "Completed" },
    { id: 117, name: "Evara Hospital", address: "Gandhinagar", owner: "Dr Niraj Suri", type: "Quality Accreditation", status: "Completed" },
    { id: 118, name: "I.G. Memorial Hospital", address: "Veraval", owner: "Dr Rajesh Ghansani", type: "Renewal", status: "In Process" },
    { id: 119, name: "Aniket Children Hospital", address: "Ahmedabad", owner: "Dr Beena Gajjar", type: "Renewal", status: "In Process" },
    { id: 120, name: "Shubh Multispeciality Hospital", address: "Kalol", owner: "Dr Ajay Gajjar", type: "Quality Accreditation", status: "In Process" },
    { id: 121, name: "Chanddni Hospital", address: "Kota, Rajasthan", owner: "Dr Kshitij Soni", type: "Quality Accreditation", status: "In Process" },
    { id: 122, name: "Gastroplus Hospital", address: "Nikol", owner: "Ms. Rukshar Kheradawala", type: "Quality Accreditation", status: "In Process" },
    { id: 123, name: "Gastroplus Digestive Centre", address: "Vastrapur", owner: "Ms. Rukshar Kheradawala", type: "Quality Accreditation", status: "In Process" },
    { id: 124, name: "Yashikas Lifecare Hospital", address: "Kosamba", owner: "Dr Bharat Gramani", type: "Quality Accreditation", status: "In Process" },
    { id: 125, name: "Alfa Gastor & Liver Care", address: "Ahmedabad", owner: "Dr Vatsal Mehta", type: "Quality Accreditation", status: "In Process" },
    { id: 126, name: "Prism Multispeciality Hospital", address: "Ahmedabad", owner: "Dr Heena Zargar", type: "Quality Accreditation", status: "In Process" },
    { id: 127, name: "Ansh Clinic", address: "Ahmedabad", owner: "Dr Sanjay Rajput", type: "Quality Accreditation", status: "In Process" },
    { id: 128, name: "Krishna Ayurvedam Panchakarma", address: "Ahmedabad", owner: "Dr Digish Thakkar", type: "Quality Accreditation", status: "In Process" },
    { id: 129, name: "ICONIC Hospital Intl", address: "Ahmedabad", owner: "Dr Parag Seth", type: "Quality Accreditation", status: "In Process" },
    { id: 130, name: "Shraddha Hospital", address: "Kalol", owner: "Dr Rajat Engineer", type: "Renewal", status: "In Process" },
    { id: 131, name: "Dheeraj Hospital", address: "Patan", owner: "Dr Vipul Soni", type: "Quality Accreditation", status: "In Process" },
    { id: 132, name: "Shivasya Hospital", address: "Ahmedabad", owner: "Dr Amit Trivedi", type: "Renewal", status: "In Process" },
    { id: 133, name: "Orthoplus Hospital", address: "Ahmedabad", owner: "Dr Pratik Shah", type: "Renewal", status: "In Process" },
    { id: 134, name: "Spectrum Advanced Eye Care", address: "Surat", owner: "Dr Nitin Garg", type: "Quality Accreditation", status: "In Process" },
    { id: 135, name: "Sattva Orthopedic & ENT", address: "Ahmedabad", owner: "Dr Satvik Patel", type: "Quality Accreditation", status: "In Process" },
    { id: 136, name: "Karmdeep Hospital", address: "Ahmedabad", owner: "Dr Neha Pethani", type: "Renewal", status: "In Process" },
    { id: 137, name: "Shailya Hospital", address: "Ahmedabad", owner: "Dr Kaushal Anand", type: "Quality Accreditation", status: "In Process" },
    { id: 138, name: "Rangam Multispeciality Hospitl", address: "Ahmedabad", owner: "Dr Rudresh Pandya", type: "Quality Accreditation", status: "In Process" },
    { id: 139, name: "Suryam Imaging Center", address: "Civil, Ahmedabad", owner: "Dr Sudhir Singh", type: "Quality Accreditation", status: "In Process" },
    { id: 140, name: "Suryam Imaging Center", address: "Narol", owner: "Dr Sunil Charpot", type: "Quality Accreditation", status: "In Process" },
    { id: 141, name: "L & T Diagnostic Centre", address: "Vadodara", owner: "Mr Rushikesh Mistry", type: "Quality Accreditation", status: "In Process" },
    { id: 142, name: "Vidhi Diagnostics", address: "Ahmedabad", owner: "Dr Dinesh Modh", type: "Quality Accreditation", status: "In Process" },
    { id: 143, name: "Dr Piyush Ayurveda", address: "Ahmedabad", owner: "Dr Piyush Patel", type: "Quality Accreditation", status: "In Process" },
    { id: 144, name: "Parshwa Dental Clinic", address: "Ahmedabad", owner: "Dr Shrenik Shah", type: "Quality Accreditation", status: "In Process" },
    { id: 145, name: "Kalp Hospital", address: "Junagadh", owner: "Dr V V Aghera", type: "Quality Accreditation", status: "In Process" },
    { id: 146, name: "Bhagwati General Hospital", address: "Ahmedabad", owner: "Dr Rahul Mali", type: "Renewal", status: "In Process" },
    { id: 147, name: "Lions Hospital", address: "Mahesana", owner: "Trustee", type: "Quality Accreditation", status: "In Process" },
    { id: 148, name: "Apollo Eye Hospital", address: "Ahmedabad", owner: "Dr Pranay Brambhatt", type: "Quality Accreditation", status: "In Process" },
    { id: 149, name: "Anjani Maternity Hospital", address: "Ankleshwar", owner: "Dr Bhoomi Dave", type: "Renewal", status: "In Process" },
    { id: 150, name: "JP Hospital", address: "Sola", owner: "Dr Jay Patel", type: "Quality Accreditation", status: "In Process" },
    { id: 151, name: "Asian Supespeciality Hospital", address: "Ahmedabad", owner: "Dr Bhupesh Patel", type: "Renewal", status: "In Process" },
    { id: 152, name: "Rhythm Heart & Medical", address: "Chandkheda", owner: "Dr Hilesh Diwan", type: "Renewal", status: "In Process" },
    { id: 153, name: "Artham Multispeciality Hospital", address: "Ahmedabad", owner: "Dr Yogesh Patel", type: "Renewal/Maintenance", status: "In Process" },
    { id: 154, name: "Mehta Eye Hospital", address: "Rajkot", owner: "Dr Ajay Mehta", type: "Renewal/Maintenance", status: "In Process" },
    { id: 155, name: "Rich NICU", address: "Disa", owner: "Dr Keshar Gadhvi", type: "Quality Accreditation", status: "In Process" },
    { id: 156, name: "Prachin Ayurveda", address: "Nikol", owner: "Dr Sachin Chauhan", type: "Quality Accreditation", status: "In Process" },
    { id: 157, name: "Heart Hospital", address: "Mehsana", owner: "Dr Alap Patel", type: "Quality Accreditation", status: "In Process" },
    { id: 158, name: "Dr Agravat Wellness Centre", address: "Ahmedabad", owner: "Dr Jaman Agravat", type: "Quality Accreditation", status: "In Process" }
];